name: Build LaTeX and deploy on GitHub Releases
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

permissions: { }

jobs:
  build-check:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bibtex-ruby

      - name: Generate bibliography
        run: |
          ruby bibtex_prettifier.rb

      - name: Compile LaTeX report
        uses: xu-cheng/latex-action@v3
        with:
          root_file: distributed-systems-final-report.tex
          args: -pdf -shell-escape -file-line-error -halt-on-error -interaction=nonstopmode
          extra_system_packages: inkscape

  publish-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bibtex-ruby

      - name: Generate bibliography
        run: |
          ruby bibtex_prettifier.rb

      - name: Compile and publish all LaTeX
        uses: DanySK/compile-and-publish-all-latex@2.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
